spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    url: jdbc:mysql:///vhr?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
  cache:
    cache-names: menus_cache
server:
  port: 8081
  compression:
    enabled: true

fastdfs:
  nginx:
    host: http://192.168.91.128/

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql